NewsPortal/NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('', include('qwe.urls')),
]

NewsPortal/qwe/urls.py
from django.urls import path
from .views import *


urlpatterns = [
   path('news/', NewsList.as_view(), name='news_list'),
   path('article/', ArticleList.as_view(), name='article_list'),
   path('post/<pk>', PostDetail.as_view(), name='post_detail'),
   path('news/<pk>', NewsDetail.as_view(), name='news_detail'),
   path('article/<pk>', ArticleDetail.as_view(), name='article_detail'),
   path('news/create/', NewsCreate.as_view(), name='news_create'),
   path('article/create/', ArticleCreate.as_view(), name='article_create'),
   path('news/<pk>/edit/', PostUpdate.as_view(), name='news_update'),
   path('article/<pk>/edit/', PostUpdate.as_view(), name='article_update'),
   path('news/<pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('article/<pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('subscriptions/', subscriptions, name='subscriptions'),
]

NewsPortal/qwe/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse


class Author(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def update_rating(self):
        self.rating = 0
        for i in self.post_set.all():
            self.rating += i.rating
        self.rating = self.rating * 3

        for i in self.author.comment_set.all():
            self.rating += i.rating

        for i in self.post_set.all():
            postcommrat = i.comment_set.aggregate(commrat=Sum('rating'))
            self.rating += postcommrat.get('commrat')
        self.save()

    def __str__(self):
        return self.author.username


class Category(models.Model):
    category = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.category.title()


class Post(models.Model):
    ARTICLE = 'AR'
    NEWS = 'NE'
    CATEGORY = (
        (ARTICLE, 'Статья'),
        (NEWS, 'Новость'),
    )

    postAuthor = models.ForeignKey(Author, on_delete=models.CASCADE)
    postType = models.CharField(max_length=2, choices=CATEGORY, default=ARTICLE)
    date = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=256)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating += -1
        self.save()

    def preview(self):
        return f'{self.text[:124]}...'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.title}: {self.text}'


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating += -1
        self.save()


class Subscription(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='subscriptions')
    category = models.ForeignKey(to='Category', on_delete=models.CASCADE, related_name='subscriptions')

    def __str__(self):
        return f'{self.category}'

NewsPortal/templates/new.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}
<h1>{{ new.title|censor }}</h1>
<h3>{{ new.date|date:'d M Y' }}</h3>
<h2>{{ new.text|censor }}</h2>

{% endblock content %}

NewsPortal/templates/news.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load custom_tags %}


{% block title %}
Новости
{% endblock title %}

{% block content %}
   <h1>Все новости</h1>
   <hr>
   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>
   {% if news %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата</td>
               <td>Текст</td>
               {% if perms.qwe.change_post or perms.qwe.delete_post %}
               <td>Действие</td>
               {% endif %}
           </tr>
           {% for news in news %}
           <tr>
               <td>{{ news.title|censor|truncatechars:15 }}</td>
               <td>{{ news.date|date:'d M Y' }}</td>
               <td>{{ news.text|truncatechars:50|censor}}</td>
               <td>
                   {% if perms.qwe.change_post %}
                   <a href="{{ news.id }}/edit/">Изменить</a>
                   {% endif %}
                   {% if perms.qwe.delete_post %}
                   <a href="{{ news.id }}/delete/">Удалить</a>
                   {% endif %}
               </td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

NewsPortal/templates/post_create.html
{% extends 'flatpages/default.html' %}


{% block content %}
<h1>Создать</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление поста</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPortal/templates/post_edit.html
{% extends 'flatpages/default.html' %}


{% block content %}
<h1>Создать/Изменить</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.category }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}